from .description import DESCRIPTION_PROMPT, QUERY_GEN_PROMPT
from .characteristics import (
    CHARACTERISTICS_HEADER,
    CHARACTERISTICS_FALLBACK,
    PACKAGING_PROMPT,
    KEY_CHARS_PROMPT,
    GAMING_KEY_CHARS_PROMPT,
    GAMING_KEY_CHARS_PROMPTS,
    RICHCONTENT_TIPS_PROMPT,
    RICHCONTENT_SLOGAN_PROMPT,
    SLOGAN_PROMPT,
    TYPE_MODEL_PROMPT,
    WB_NAME_PROMPT,
    OZON_NAME_PROMPT,
    HASHTAG_PROMPT,
)
from .rarity import RARITY_CONTENT_PLAN_PROMPT

__all__ = [
    "DESCRIPTION_PROMPT",
    "QUERY_GEN_PROMPT",
    "CHARACTERISTICS_HEADER",
    "CHARACTERISTICS_FALLBACK",
    "PACKAGING_PROMPT",
    "KEY_CHARS_PROMPT",
    "GAMING_KEY_CHARS_PROMPT",
    "GAMING_KEY_CHARS_PROMPTS",
    "RICHCONTENT_TIPS_PROMPT",
    "RICHCONTENT_SLOGAN_PROMPT",
    "SLOGAN_PROMPT",
    "TYPE_MODEL_PROMPT",
    "WB_NAME_PROMPT",
    "OZON_NAME_PROMPT",
    "HASHTAG_PROMPT",
    "RARITY_CONTENT_PLAN_PROMPT",
]
